messages:
  mines:
    already_created: "&cMine %mine% is already created!"
    mine_not_found: "&cMine not found!"

    use_worldedit: "&cPlease, use WorldEdit for place points!"
    set_point: "&fPoint established!"
    not_placed: "&cPoints not placed!"

    points_not_setted: "&fPoints not established!"
    region_not_found: "&fRegion not found!"
    many_points: "&cThere can be no more than 2 points!"

    created: "&fMine &e%mine% &fcreated!"
    deleted: "&fMine &e%mine% &fdeleted!"
    reseted: "&fMine &e%mine% &freseted!"

    not_fit: "&fBlock &e%block% &fnot found in mine &e%mine%&f!"
    set: "&fBlock &e%block% &fin mine &e%mine% &fsetted to &e%percentage%%&f!"
    remove: "&fBlock &e%block% &fremoved from mine &e%mine%&f!"

    mine_list: "&fMine list:"

    stats: "&fStats location of mine %mine% established to current position!"
    reset_delay: "&fReset time of mine %mine% changed to &e%time%s&f!"

    invalid_mine_type: "&cInvalid mine type (CUBOID/OVERLAY)!"

  for_players: "&cOnly players can use this command!"
  no_permissions: "&cSorry, but you don't have permissions to this command!"
  not_an_integer: "&cThe number is not an integer!"

mine:

  blocks_drop_to_inventory: true

  use_holograms: true
  use_worldedit: false

  # if server has plugin HologramList
  hologram:
    - "Mine"
    - " "
    - "Name: %mine%"
    - "Time to reset: %to_reset%"
    - " "
    - "Blocks in mine: %total_blocks_in_mine%"
    - "Blocks mined: %blocks_mined%"